/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Software Module Options
 */
#define __CONFIG_NAT__ 1
#undef  __CONFIG_URLFILTER__
#define __CONFIG_DHCPC__ 1
#define __CONFIG_DHCPC_NUM__ (1)
#define __CONFIG_DHCPD__ 1
#define __CONFIG_PPPOE__ 1
#undef  __CONFIG_L2TP__
#undef  __CONFIG_PPTP__
#undef  __CONFIG_PPPOE2__
#undef  __CONFIG_8021X__
#undef  __CONFIG_TENDA_WLJB__
#undef  __CONFIG_TENDA_MULTI__
#undef  __CONFIG_TENDA_OEM__
#undef  __CONFIG_STAR_WARS_ENABLE__
#undef  __CONFIG_TENDA_CD_RTSP_IPTV__
#define __CONFIG_PPP__ 1
#define __CONFIG_CHAPMS__ 1
#define __CONFIG_CHINA_NET_CLIENT__ 1
#undef  __CONFIG_LCP_PASSIVE_ECHO_MODE__
#define __CONFIG_LCP_ECHO_INTERVAL__ (30)
#define __CONFIG_MAX_LCP_ECHO_FAILS__ (5)
#define __CONFIG_DNSMASQ__ 1
#define __CONFIG_DNSMASQ_HOSTS_NUM__ (16)
#define __CONFIG_AUTO_DNS_NUM__ (3)
#define __CONFIG_LIBUPNP__ 1
#define __CONFIG_IGD__ 1
#define __CONFIG_UPNP_modelName__ "Wireless-N Router"
#define __CONFIG_UPNP_manufacturer__ "Tenda"
#define __CONFIG_UPNP_link__ "http://www.tenda.com.cn"
#define __CONFIG_UPNP_modelNumber__ "Wireless-N Router"
#define __CONFIG_UPNP_modelDescription__ "Wireless-N Broadband Router"
#undef  __CONFIG_WPS__
#define __CONFIG_TENDA_HTTPD__ 1
#undef  __CONFIG_HTTPD__
#define __CONFIG_DEFAULT_PAGE__ "index.asp"
#define __CONFIG_WEB_DIR__ "tenda-ucd-cn"
#define __CONFIG_WEB_REALM__ "Wireless-N Router"
#define __CONFIG_WEB_VERSION__ "cn"
#define __CONFIG_Tenda_DEFAULT_PROFILE__ "tenda_sdw_n300v2_cn.c"
#define __CONFIG_WEBS_PAGE_ROM__ 1
#define __CONFIG_STREAM_STATISTIC__ 1
#define __CONFIG_TC__ 1
#define __CONFIG_TC_STAT__ 1
#undef  __CONFIG_TC_TAIL_DROP__
#define __CONFIG_TC_WINDOWS__ 1
#define __CONFIG_TC_RANDOM_DROP__ 1
#define __CONFIG_LED__ 1
#define __CONFIG_SYS_LED__ 1
#undef  __CONFIG_WPS_LED__
#undef  __CONFIG_WL_LED__
#undef  __CONFIG_NAT_DEBUG__
#undef  __CONFIG_NETBOOT__
#define __CONFIG_SYSLOG_LOG_NUM__ (150)
#define __CONFIG_SYSLOG_LOG_SIZE__ (128)
#undef  __CONFIG_TELNETD__
#undef  __CONFIG_DDNS__
#undef  __CONFIG_A5__
#define __CONFIG_BATCH_UPGRADE__ 1
#undef  __CONFIG_TENDA_HTTPD_UCD_MULTI_EN__
#undef  __CONFIG_AL_SECURITY__
#undef  __CONFIG_ALINKGW__
#undef  __CONFIG_ALINKGW_V2__
#define __CONFIG_TENDA_HTTPD_UCD__ 1
#undef  __CONFIG_TENDA_HTTPD_V3__
#undef  __CONFIG_TENDA_HTTPD_NORMAL__
#undef  __CONFIG_AUTO_CONN__

/*
 * Internal Software Module Options
 */
#define __CONFIG_UTILS__ 1

/*
 * HQW ADD Module Options
 */
#define __CONFIG_RESTART_CHECK__ 1
#undef  __CONFIG_PPPOE_AUTO_MTU__
#undef  __CONFIG_SUPPORT_GB2312__
#undef  __CONFIG_TCP_AUTO_MTU__
#undef  __CONFIG_EASE_DEBUG__
#define __CONFIG_NEW_INFRASTRUCTURE__ 1
#define __CONFIG_WIFI_STATUS_CHECK__ 1
#undef  __CONFIG_APCLIENT_DHCPC__
#undef  __CONFIG_NEW_WAN_STATUS__
#define __CONFIG_MEMORY_SIZE__ (16)
#undef  __CONFIG_DNS_8_8_8_8_SUPPORT__
