#ifndef CYGONCE_PKGCONF_ATHTTPD_H
#define CYGONCE_PKGCONF_ATHTTPD_H
/*
 * File athttpd.h
 * Write by manual
 *
 */

#define CYGNUM_NET_ATHTTPD_THREADOPT_PRIORITY 16
#define CYGNUM_NET_ATHTTPD_THREADOPT_PRIORITY_16
#define CYGNUM_NET_ATHTTPD_THREADOPT_STACKSIZE 8192
#define CYGNUM_NET_ATHTTPD_THREADOPT_STACKSIZE_8192
#define CYGNUM_NET_ATHTTPD_SERVEROPT_PORT 80
#define CYGNUM_NET_ATHTTPD_SERVEROPT_PORT_80
#define CYGDAT_NET_ATHTTPD_SERVEROPT_SERVERID "eCos Embedded Web Server"
#define CYGNUM_ATHTTPD_SERVER_BUFFER_SIZE 2048
#define CYGNUM_ATHTTPD_SERVER_BUFFER_SIZE_2048
#define CYGNUM_ATHTTPD_SERVER_MAX_POST 2048000
#define CYGNUM_ATHTTPD_SERVER_MAX_POST_2048000
#ifdef HAVE_IRES_WEB
#define CYGDAT_NET_ATHTTPD_SERVEROPT_ROOTDIR ""
#else
#define CYGDAT_NET_ATHTTPD_SERVEROPT_ROOTDIR "/web/"
#endif
#define CYGDAT_NET_ATHTTPD_SERVEROPT_ERRORDIR "errors/"
#define CYGDAT_NET_ATHTTPD_DEFAULT_MIME_TYPE "text/plain"
#define CYGDAT_NET_ATHTTPD_ALTERNATE_HOME "/index.html"
#ifdef HAVE_IRES_WEB
#else
#define CYGOPT_NET_ATHTTPD_USE_FS 1
#endif
#define CYGOPT_NET_ATHTTPD_USE_AUTH 1
#define CYGOPT_NET_ATHTTPD_CLOSE_CHUNKED_CONNECTIONS 1
#define CYGOPT_NET_ATHTTPD_DOCUMENT_EXPIRATION_TIME 0
#define CYGOPT_NET_ATHTTPD_DOCUMENT_EXPIRATION_TIME_0
#define CYGOPT_NET_ATHTTPD_USE_ASP 1
#define CYGOPT_NET_ATHTTPD_DEBUG_LEVEL 0
#define CYGOPT_NET_ATHTTPD_DEBUG_LEVEL_2
#define REDIRECT_FORM_NAME					"formRedirect.htm"

#define CONFIG_RTL_SUPPORT_MULTIPART
#ifndef MSG_BUFFER_SIZE
#define MSG_BUFFER_SIZE 256
#endif

#define CYG_HTTPD_STATUS_OK                      200
#define CYG_HTTPD_STATUS_MOVED_PERMANENTLY       301
#define CYG_HTTPD_STATUS_MOVED_TEMPORARILY       302
#define CYG_HTTPD_STATUS_NOT_MODIFIED            304
#define CYG_HTTPD_STATUS_BAD_REQUEST             400
#define CYG_HTTPD_STATUS_NOT_AUTHORIZED          401
#define CYG_HTTPD_STATUS_FORBIDDEN               403
#define CYG_HTTPD_STATUS_NOT_FOUND               404
#define CYG_HTTPD_STATUS_METHOD_NOT_ALLOWED      405
#define CYG_HTTPD_STATUS_SYSTEM_ERROR            500
#define CYG_HTTPD_STATUS_NOT_IMPLEMENTED         501

#endif
