/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * BSP Library (CPU) Select
 */
#define CONFIG_MIPS_BRCM 1
#define CONFIG_BCM947XX 1
#define CONFIG_ECC "ecc-bcm947xx-router-tiny"

/*
 * Hardware Configuration
 */
#undef  CONFIG_WATCHDOG

/*
 * Software Module Options
 */
#define CONFIG_VLAN 1
#define CONFIG_BRIDGE 1
#define CONFIG_NUM_BRIDGES (1)
#define CONFIG_PPP_NUM_SESSIONS (3)
#define CONFIG_NAT_LINKS (2048)

/*
 * Device Drivers Options
 */
#define CONFIG_ET_47XX 1
#undef  CONFIG_BCM57XX
#define CONFIG_WL 1
#define CONFIG_WL_USE_AP 1
#undef  CONFIG_WL_USE_STA
#undef  CONFIG_WL_USE_APSTA
#define CONFIG_WL_AP "wlconfig_ecos_router_ap_5357"
#define CONFIG_WL_STA "wlconfig_ecos_router_sta_5357"
#define CONFIG_WL_APSTA "wlconfig_ecos_router_apsta_5357"
