#!/bin/sh

OS_NAME=`uname | grep Linux`
LINUX_VERSION=`uname -r | grep 2.4`

echo "$LINUX_VERSION"

if [ "$OS_NAME" = "" ]; then
./lzma-cyg.exe $1 $2 $3
elif [ "$OS_NAME" != "" ]; then
if [ "$LINUX_VERSION" = "" ]; then
./lzma-26 $1 $2 $3
elif [ "$LINUX_VERSION" != "" ]; then
./lzma-24 $1 $2 $3
else
echo "can not find LZMA"
fi
fi
