TR069SRC = src
#TOOLCHAINPATH	=/home/Partrick_cai/ecos_20120606/gnutools/mips-elf/bin
#CC	= $(TOOLCHAINPATH)/mips-elf-gcc
#STRIP	= $(TOOLCHAINPATH)/mips-elf-strip
#LD	= $(TOOLCHAINPATH)/mips-elf-ld
#AR	= $(TOOLCHAINPATH)/mips-elf-ar

all:
	make -C $(TR069SRC)

clean:
	make -C $(TR069SRC) clean
